### ISSUE TITLE
Todo: Team

### ISSUE THREAD

**Issue by cheng-kang** [cheng-kang/React-Native-Dev#3]
- [ ] Create Team / Update Team
- [ ] Apply for a Team
- [ ] Accept an applicant
- [ ] Remove a Team member
- [ ] Team Chat
