### ISSUE TITLE
Todo: Organizer

### ISSUE THREAD

**Issue by cheng-kang** [cheng-kang/React-Native-Dev#4]
- [ ] Organizer Sign Up/ Sign In Page
- [ ] Create Event Page
- [ ] Event List Page (events created by current organizer)
- [ ] Event Detail Page (event created by current organizer)
- [ ] Update Event / Delete Event (inside Event Detail Page)
- [ ] Chat with people registered for events (created by current organizer)
